server:
  port: 9000

spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/user_registration
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true